language: node_js
node_js:
  - '0.10'
before_script:
  - gem update --system
  - gem install compass
  - npm install -g bower grunt-cli
  - bower install
  - cp "test/utils/protractor.js" "node_modules/protractor/lib/protractor.js"
